### ISSUE TITLE
Create new disk_type variable

### ISSUE THREAD

**Issue by ssilva-soap** [Privatehive/gcp-hosted-github-runner#1]
GCP now has some kind of VMs that only accept SSD disks.
As the disk_type is a fixed value "pd-standard" we can use size like "c4-highcpu"

The proposed solution is to implements disk_type as a variable

**Comment by Tereius** [comment]
Done:
https://github.com/Privatehive/gcp-hosted-github-runner/commit/5001a86fbf92322ab3b1d0ec71bce46b116e0a19
